name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt

      - name: Run smoke test (start app and call /products)
        run: |
          cd backend
          # start uvicorn in background
          python -m uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          PID=$!
          # wait for the server to start (retry)
          n=0
          until curl -sSf http://127.0.0.1:8000/products || [ $n -gt 10 ]; do
            n=$((n+1))
            sleep 1
          done
          # call endpoint and assert non-empty response
          curl -sSf http://127.0.0.1:8000/products | python -c "import sys,json; data=json.load(sys.stdin); assert isinstance(data, list); print('smoke ok')"
          kill $PID
        shell: bash
